project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pages/admin/*.qmd
    - pages/chapters/*.qmd
    - slides/*.qmd
    - pages/exercises/exercise_*.qmd
    - pages/solutions/solution_*.qmd


website:
  title: "Neurowissenschaft Computerlab"
  site-url: https://kogpsy.github.io/neuroscicomplabFS23/
  favicon: /assets/logo_landing.png
  reader-mode: true

  navbar:
    logo: /assets/logo.png
    background: primary

    left:
        - text: "ğŸ“š Syllabus"
          file: pages/admin/syllabus.qmd
        - text: "ğŸ“ Leistungsnachweise"
          file: pages/admin/leistungsnachweise.qmd
        - text: "ğŸ‘¨ğŸ»â€ğŸ«ğŸ‘©ğŸ¼â€ğŸ”¬ Dozierende"
          file: pages/admin/dozierende.qmd
      # - text: ğŸ—„ï¸ Admin
      #   menu:
      #     - pages/admin/syllabus.qmd
      #     - pages/admin/leistungsnachweise.qmd
      #     - pages/admin/dozierende.qmd
      # - text: Kapitel
      #   menu:
      #     - pages/chapters/01_psychopy_experiments.qmd
      #     # - pages/chapters/02_importing_data.qmd
      #     # - pages/chapters/03_data_cleaning.qmd
      #     # - pages/chapters/04_summarizing_data.qmd
      #     # - pages/chapters/05_signal_detection_i.qmd
      #     # - pages/chapters/06_signal_detection_ii.qmd
      #     # - pages/chapters/07_response_times_i.qmd
      #     # - pages/chapters/08_response_times_ii.qmd
      #     # - pages/chapters/09_evidence_accumulation_1.qmd
      #     # - pages/chapters/10_evidence_accumulation_2.qmd
      #     # - pages/chapters/11_data-analysis-1.qmd
      #     # - pages/chapters/12_data-analysis-2.qmd

      # - text:  ğŸ“½ï¸ Slides
      #   menu:
      #     - text: "1. Sitzung (22.02.2022)"
      #       file: slides/01_introduction.qmd


      # - text: Ãœbungen
      #   menu:
      #     - pages/exercises/exercise_01.qmd


      # - text: LÃ¶sungen
      #   menu:
      #       - pages/solutions/solution_03.qmd

  sidebar:
    style: "floating"
    # style: "docked"
    search: true
    contents:
      - section: "EinfÃ¼hrung"
        contents:
          - pages/chapters/software.qmd
          - pages/chapters/chatgpt.qmd


      - section: "Experimente"
        contents:
          # - pages/admin/02_syllabus.qmd
          # - pages/admin/03_software.qmd
          # - pages/admin/04_leistungsnachweise.qmd
      - section: "Data wrangling"
        contents:
          # - pages/admin/02_syllabus.qmd
          # - pages/admin/03_software.qmd
          # - pages/admin/04_leistungsnachweise.qmd
      - section: "Visualisieren"
        contents:
          # - pages/admin/02_syllabus.qmd
          # - pages/admin/03_software.qmd
          # - pages/admin/04_leistungsnachweise.qmd
      - section: "Signal detection"
        contents:
          # - pages/admin/02_syllabus.qmd
          # - pages/admin/03_software.qmd
          # - pages/admin/04_leistungsnachweise.qmd
      - section: "Reaktionszeiten"
        contents:
          # - pages/admin/02_syllabus.qmd
          # - pages/admin/03_software.qmd
          # - pages/admin/04_leistungsnachweise.qmd
      - section: "Bayesianische Datenanalyse"
        contents:
          # - pages/admin/02_syllabus.qmd
          # - pages/admin/03_software.qmd
          # - pages/admin/04_leistungsnachweise.qmd

  page-footer:
    left: "Â© Copyright 2023, Andrew Ellis & Gerda Wyssen"
    right:
      - icon: github
        href: https://github.com/kogpsy/neuroscicomplabFS23

format:
  html:
    theme:
      light: [flatly, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    css: /styles/global.css
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex

execute:
  cache: true
  freeze: auto

callout-icon: true
callout-tip-caption: "LÃ¶sung"
callout-note-caption: "Vertiefung"
callout-important-caption: "Ãœbung"
callout-caution-caption: "Hinweis"

editor: source
