project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pages/admin/*.qmd
    - pages/chapters/*.qmd
    - slides/*.qmd
    - pages/exercises/exercise_*.qmd
    - pages/solutions/solution_*.qmd


website:
  title: "Neurowissenschaft Computerlab"
  site-url: https://kogpsy.github.io/neuroscicomplabFS23/
  favicon: /assets/logo_landing.png
  reader-mode: true

  navbar:
    logo: /assets/logo.png
    background: primary

    right:
        - text: ğŸ—„ï¸ Admin
          menu:
            - text: "ğŸ“š Syllabus"
              file: pages/admin/syllabus.qmd
            - text: "ğŸ“ Leistungsnachweise"
              file: pages/admin/leistungsnachweise.qmd
            - text: "ğŸ‘¨ğŸ»â€ğŸ«ğŸ‘©ğŸ¼â€ğŸ”¬ Dozierende"
              file: pages/admin/dozierende.qmd
  sidebar:
    style: "floating"
    # style: "docked"
    search: true
    contents:
      - section: "EinfÃ¼hrung"
        contents:
          - pages/chapters/software.qmd
          - pages/chapters/chatgpt.qmd
          - pages/chapters/datacamp.qmd


      - section: "Experimente"
        contents:
          - pages/chapters/psychopy_experiments.qmd
          - pages/chapters/experiment_stepbystep.qmd
          - pages/chapters/uebung_1_experiment.qmd

      - section: "Data wrangling"
        contents:
          - pages/chapters/reproducibility.qmd
          - pages/chapters/importing_data.qmd
          - pages/chapters/functions-loops.qmd
          - pages/chapters/importing_data-2.qmd
          - pages/chapters/summarizing-data.qmd
          - pages/chapters/uebung_2_data_wrangling.qmd

      - section: "Visualisieren"
        contents:
          - pages/chapters/rmarkdown.qmd
          - pages/chapters/data_visualization_1.qmd
          - pages/chapters/data_visualization_2.qmd
          - pages/chapters/uebung_3_data_visualization.qmd

      - section: "Signal detection"
        contents:
          - pages/chapters/signal-detection-1.qmd

      - section: "Bayesianische Datenanalyse"
        contents:
          # - pages/admin/02_syllabus.qmd

  page-footer:
    # left: "Â© Copyright 2023, Andrew Ellis & Gerda Wyssen"
    right:
      - icon: github
        href: https://github.com/kogpsy/neuroscicomplabFS23

format:
  html:
    theme:
      light: [flatly, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    css: /styles/global.css
    link-external-newwindow: true
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: preamble.tex

execute:
  cache: true
  freeze: true
  execute-dir: project

callout-icon: true
callout-tip-caption: "LÃ¶sung"
callout-note-caption: "Vertiefung"
callout-important-caption: "Hands-on"
callout-caution-caption: "Hinweis"

editor:
  render-on-save: true
